### ISSUE TITLE
LICENSE is missing in repo.

### ISSUE THREAD

**Issue by mjscosta** [sgerrand/docker-glibc-builder#29]
Hi @sgerrand I'd like fork the and consider multi arch builds.

I've noticed there's no LICENSE in the repo, I know this might be an annoying issue, but according to github [No License](https://choosealicense.com/no-permission/), means on legal terms we cannot share and contribute.

Thanks

**Comment by sgerrand** [comment]
There's a stanza on the page you linked to:

> For example, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service, by which you allow others to view and fork your repository.

In case this isn't clear to you, the above explicitly means you can fork this repository and contribute patches.

**Comment by mjscosta** [comment]
This is not really much relevant for me. I'd thank you for providing the binary packages and sharing them, those are under GPL or LGPL.

But so to clarify, if you use github you accept the terms to enable service functionality, including these things:
> For example, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service, by which you allow others to view and fork your repository.

Also refered as on the section [D.3](
https://help.github.com/articles/github-terms-of-service/#3-ownership-of-content-right-to-post-and-license-grants) of the terms:

If you see the text that follows, also in accordance with [D.5](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users):
>Neither site terms nor jurisdiction-specific copyright limitations are sufficient for the kinds of collaboration that people usually seek on a public code host, such as experimentation, modification, and sharing as fostered by an open source license.

**Comment by greenlaw** [comment]
@sgerrand - To echo @mjscosta - I would love to use your code in a project, but without an explicitly defined license, I am unable to do so.  Even though the repository is public and forkable, actually using and/or modifying the code is problematic without a license.  

I see that your related repository [alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc) (which uses binaries built by this repository) has defined the license as LGPL in the APKBUILD file, so I am guessing your intent is to license this repository under LGPL as well, but until it is explicitly defined I can only assume.

Would you please consider adding a LICENSE file to this repository (and ideally, to your alpine-pkg-glibc repo as well) explicitly stating the license type and version? (e.g. [LGPL 3.0](https://choosealicense.com/licenses/lgpl-3.0/))

**Comment by sgerrand** [comment]
To you both:

How are you planning on using this code in a project? While I understand
the need for licensing being attached to the packages containing binaries
compiled by this repository, the code here is just running `./configure`
and `make`. Please let me know when you can.

>

**Comment by greenlaw** [comment]
I am planning to install Oracle JDK (which requires glibc) in a Docker image based on Alpine.  However, I need to follow IT security restrictions which would disallow me from using your pre-built binaries, so I'd like to fork your glibc repo and modify it by including this glibc build process as a preliminary step in a multi-stage docker build.  

I can certainly write my own builder, but I would prefer to start with your working solution if possible.  If you don't want to license it, I'll go the build-my-own path, but thought I would ask first.  

Anyway, thanks for considering.
