### ISSUE TITLE
What are the actual steps to install the output tar.gz file into the OS?

### ISSUE THREAD

**Issue by Stiverton** [sgerrand/docker-glibc-builder#53]
Title

**Comment by sgerrand** [comment]
Whether intended or not, your question has a pretty large surface area. I suggest you refer to the [documentation for the GNU C Library](https://sourceware.org/glibc/wiki), specifically [how to install it](https://sourceware.org/glibc/wiki/FAQ#How_do_I_install_all_of_the_GNU_C_Library_project_libraries_that_I_just_built.3F).
